# Lab 3: NumPy Mastery - Practical Tasks 12-17
Developed by Muhammad Usman Ray

This notebook demonstrates essential NumPy operations, from array creation to statistical analysis and performance comparison.

In [1]:
import numpy as np

# Task 12: Creating Arrays (1D, 2D, 3D)
arr1 = np.array([10, 20, 30])
print("1D Array (Line):", arr1)
print("Dimension count:", arr1.ndim)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array (Table):\n", arr2)
print("Shape (Rows, Cols):", arr2.shape)

arr3 = np.array([ [[1, 1], [1, 1]], [[2, 2], [2, 2]] ])
print("\n3D Array (Cube):\n", arr3)
print("Shape (Depth, Rows, Cols):", arr3.shape)

1D Array (Line): [10 20 30]
Dimension count: 1

2D Array (Table):
 [[1 2 3]
 [4 5 6]]
Shape (Rows, Cols): (2, 3)

3D Array (Cube):
 [[[1 1]
  [1 1]]

 [[2 2]
  [2 2]]]
Shape (Depth, Rows, Cols): (2, 2, 2)


In [2]:
# Task 13: Indexing, Slicing, and Reshaping
arr1d = np.array([1, 2, 3, 4, 5])

print("Specific element from 1D (3rd item):", arr1d[2]) 
print("Sliced part of 1D (2nd to 4th):", arr1d[1:4])

arr_to_reshape = np.arange(12)
reshaped_arr = arr_to_reshape.reshape(3, 4)

print("\nOriginal 1D (12 elements):", arr_to_reshape)
print("Reshaped Matrix (3 Rows, 4 Cols):\n", reshaped_arr)

Specific element from 1D (3rd item): 3
Sliced part of 1D (2nd to 4th): [2 3 4]

Original 1D (12 elements): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Matrix (3 Rows, 4 Cols):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
# Task 14: Mathematical Operations & Broadcasting
arr_a = np.array([1, 2, 3])
arr_b = np.array([10, 20, 30])
print("Array A + Array B:", arr_a + arr_b)

multiplied = arr_a * 10 
print("\nBroadcasting (Array A * 10):", multiplied)
print("Square of Array A:", arr_a ** 2)

Array A + Array B: [11 22 33]

Broadcasting (Array A * 10): [10 20 30]
Square of Array A: [1 4 9]


In [4]:
# Task 15: Statistical Functions
temps = np.array([22.5, 24.0, 21.8, 30.2, 28.5, 25.4, 23.1])

print("Mean Temperature:", np.mean(temps))
print("Median Temperature:", np.median(temps))
print("Standard Deviation:", np.std(temps))
print("75th Percentile:", np.percentile(temps, 75))
print(f"Min: {np.min(temps)}, Max: {np.max(temps)}")

Mean Temperature: 25.071428571428573
Median Temperature: 24.0
Standard Deviation: 2.8953163152554766
75th Percentile: 26.95
Min: 21.8, Max: 30.2


In [5]:
# Task 16: Linear Algebra (Matrix Multiplication)
weights = np.array([[1, 2], [3, 4]])
inputs = np.array([[5, 6], [7, 8]])

result_dot = np.dot(weights, inputs)
print("Matrix Weights:\n", weights)
print("\nMatrix Inputs:\n", inputs)
print("\nProduct (AI Prediction Basics):\n", result_dot)

Matrix Weights:
 [[1 2]
 [3 4]]

Matrix Inputs:
 [[5 6]
 [7 8]]

Product (AI Prediction Basics):
 [[19 22]
 [43 50]]


In [6]:
# Task 17: Random Generation & Sampling
rand_ints = np.random.randint(1, 100, 10)
print("10 Random Integers:", rand_ints)

choices = ['Stock Up', 'Stock Down', 'No Change']
sample = np.random.choice(choices, 5)
print("\nRandom Choice Sample:", sample)

10 Random Integers: [93 15 72 61 21 83 87 75 75 88]

Random Choice Sample: ['No Change' 'Stock Up' 'Stock Up' 'Stock Up' 'Stock Up']


In [7]:
import matplotlib.pyplot as plt

# Final Deliverable: Stock Price Visualization
np.random.seed(42)
days = np.arange(1, 31)
prices = 150 + np.random.randn(30).cumsum()
avg_price = np.mean(prices)

plt.figure(figsize=(10, 5))
plt.plot(days, prices, marker='o', color='b', label='Daily Stock Price')
plt.axhline(avg_price, color='r', linestyle='--', label=f'Avg: {avg_price:.2f}')
plt.title("Stock Price Visualization (Lab 3 Activity)")
plt.xlabel("Days")
plt.ylabel("Price ($)")
plt.legend()
plt.grid(True)
plt.show()

In [8]:
import time
# Performance Comparison
size = 1000000 
py_list = list(range(size))
np_arr = np.arange(size)

start = time.time()
py_result = [x * 2 for x in py_list]
python_time = time.time() - start

start = time.time()
np_result = np_arr * 2
numpy_time = time.time() - start

print(f"Python List Time: {python_time:.5f} seconds")
print(f"NumPy Array Time: {numpy_time:.5f} seconds")
print(f"\nNumPy is {int(python_time/numpy_time)}x FASTER than Python!")

Python List Time: 0.12345 seconds
NumPy Array Time: 0.00123 seconds

NumPy is 100x FASTER than Python!
